In [16]:
# Lecture 2 Part 2
# Find the Maximum 
import numpy as np
n=10
x=np.random.uniform(low=0.0, high=100.0, size=n)
m=float('-inf')   
for i in range(len(x)):
    if m<x[i]:
        m=x[i]
print(x)        
print("max=%f"%m)

# Devision of discrete good among given number of consumers


# heap's algorithm:
# Algorithm:The algorithm generates (n-1)! permutations of the first n-1 elements, adjoining the last 
# element to each of these. This will generate all of the permutations that end with the last element.
# If n is odd, swap the first and last element and if n is even, then swap the ith element (i is the counter 
# starting from 0) and the last element and repeat the above algorithm till i is less than n.
# In each iteration, the algorithm will produce all the permutations that end with the current last element.

# Use of yield: 

# Simple code to do permutation:
from itertools import permutations 
l = list(permutations(range(1,4))) 
print(l) 
# permutations('ABCD', 2)  N choose 2

[33.01492583 18.66966961  0.11447384 32.26304258 83.01864668 63.71744054
 48.25344109 94.66387487 42.5699778  33.46914637]
max=94.663875
[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [12]:
# Python program to print all permutations with 
# duplicates allowed 

def toString(List): 
    return ''.join(List) 

# Function to print permutations of string 
# This function takes three parameters: 
# 1. String 
# 2. Starting index of the string 
# 3. Ending index of the string. 
def permute(a, l, r): 
    if l==r: 
        print(toString(a)) 
    else: 
        for i in range(l,r+1): 
            a[l], a[i] = a[i], a[l] 
            permute(a, l+1, r) 
            a[l], a[i] = a[i], a[l] # backtrack 

# Driver program to test the above function 
string = "ABC"
n = len(string) 
a = list(string) 
permute(a, 0, n-1) 

# This code is contributed by Bhavya Jain 


ABC
ACB
BAC
BCA
CBA
CAB


In [2]:
import random, numpy, math, copy, matplotlib.pyplot as plt
cities = [random.sample(range(100), 2) for x in range(15)]
tour = random.sample(range(15),15)
for temperature in numpy.logspace(0,5,num=100000)[::-1]:
    [i,j] = sorted(random.sample(range(15),2))
newTour =  tour[:i] + tour[j:j+1] +  tour[i+1:j] + tour[i:i+1] + tour[j+1:]
if math.exp( ( sum([ math.sqrt(sum([(cities[tour[(k+1) % 15]][d] - cities[tour[k % 15]][d])**2 for d in [0,1] ])) for k in [j,j-1,i,i-1]]) - sum([math.sqrt(sum([(cities[newTour[(k+1) % 15]][d] - cities[newTour[k % 15]][d])**2 for d in [0,1] ])) for k in [j,j-1,i,i-1]])) / temperature) > random.random():
    tour = copy.copy(newTour)
plt.plot([cities[tour[i % 15]][0] for i in range(16)], [cities[tour[i % 15]][1] for i in range(16)], 'xb-')
plt.show()

<Figure size 640x480 with 1 Axes>

In [ ]:
# Week 4 lecture review

# define a random matrix and generate market equilibrium
np.linalg.solve() # solve matrix 


# Minimize a linear function
scipy.optimize.linprog
scipy.optimize.linprog(c, A_ub=None, b_ub=None, A_eq=None, b_eq=None, bounds=None, method='simplex', callback=None, options=None)[source]
Minimize a linear objective function subject to linear equality and inequality constraints.

Linear Programming is intended to solve the following problem form:

Minimize: c^T * x

Subject to: A_ub * x <= b_ub
A_eq * x == b_eq

# SciPy 2017 Tutorial on NumPy https://www.youtube.com/watch?v=lKcwuPnSHIQ&ab_channel=Enthought

In [1]:
# Week 5 Lecture review Mathematical optimization with Python
import numpy as np
x = np.arange(-5, 5, 0.1)
y = np.arange(-5, 5, 0.1)
xx, yy = np.meshgrid(x, y, sparse=True)
z = np.sin(xx**2 + yy**2) / (xx**2 + yy**2)
h = plt.contourf(x,y,z)

NameError: name 'plt' is not defined

In [ ]:
# Week 7 Lecture Review Interpolation and integration

# Spline interpolation and polynomial interpolation:
# Difference: Spline interpolation uses low-degree polynomials in each of the intervals, 
# and chooses the polynomial pieces such that they fit smoothly together.
# The resulting function is called a spline.

# Generally, if we have n data points, there is exactly one polynomial of degree at most n−1 going through 
# all the data points. The interpolation error is proportional to the distance between the data points to the
# power n. Furthermore, the interpolant is a polynomial and thus infinitely differentiable. So, we see that 
# polynomial interpolation overcomes most of the problems of linear interpolation.

# However, polynomial interpolation also has some disadvantages. Calculating the interpolating polynomial
# is computationally expensive (see computational complexity) compared to linear interpolation. 

In [6]:
import numpy as np
np.random.seed(1)
for i in range(10):
    # generate sequence of five numbers
    r = np.random.uniform(1,10,5)
    print(r)

[4.75319804 7.48292044 1.00102937 3.72099315 2.32080302]
[1.83104735 2.6763419  4.11004654 4.57090727 5.84935061]
[4.77275063 7.1669755  2.84007025 8.90305693 1.24648834]
[7.03420759 4.75574322 6.02820846 2.26348245 2.7829134 ]
[8.20670112 9.71435418 3.8208176  7.23090354 8.88750237]
[9.05145997 1.7653979  1.35149305 2.52847378 8.90328253]
[1.8851215  4.78996863 9.62100577 5.79848756 7.22689403]
[3.83964068 7.17850835 8.51163105 1.1645945  7.75129883]
[9.8997498  7.73349089 3.52399593 8.10351396 1.92903406]
[5.03104174 9.17735953 3.64252734 3.58997805 2.17025715]
